# Safe-Spac Core API Configuration
server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

data:
  directory: "/data"
  authelia_users: "/authelia/users_database.yml"
  backup_interval: "24h"

security:
  jwt_secret: "${JWT_SECRET:your-secret-key-change-in-production}"
  password_min_length: 8
  captcha_expiration: "10m"
  max_login_attempts: 5
  lockout_duration: "15m"

vpn:
  provisioner_url: "http://wg-provisioner:8081"
  default_subnet: "10.0.0.0/24"
  max_clients: 100

teamspeak:
  server_query_port: 10011
  server_query_user: "${TS_QUERY_USER:serveradmin}"
  server_query_password: "${TS_QUERY_PASSWORD:}"
  server_port: 9987

logging:
  level: "info"
  format: "json"
  output: "stdout"

cors:
  allowed_origins: ["*"]
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers: ["Origin", "Content-Type", "Accept", "Authorization"]
  allow_credentials: true
  max_age: 86400
